const Comarcas = [
    { codi: '01', nom: "ALT CAMP" },
    { codi: '02', nom: "ALT EMPORDA" },
    { codi: '03', nom: "ALT PENEDES" },
    { codi: '04', nom: "ALT URGELL" },
    { codi: '05', nom: "ALTA RIBAGORÇA" },
    { codi: '06', nom: "ANOIA" },
    { codi: '07', nom: "BAGES" },
    { codi: '08', nom: "BAIX CAMP" },
    { codi: '09', nom: "BAIX EBRE" },
    { codi: '10', nom: "BAIX EMPORDA" },
    { codi: '11', nom: "BAIX LLOBREGAT" },
    { codi: '12', nom: "BAIX PENEDES" },
    { codi: '13', nom: "BARCELONES" },
    { codi: '14', nom: "BERGUEDA" },
    { codi: '15', nom: "CERDANYA" },
    { codi: '16', nom: "CONCA DE BARBERA" },
    { codi: '17', nom: "GARRAF" },
    { codi: '18', nom: "GARRIGUES" },
    { codi: '19', nom: "GARROTXA" },
    { codi: '20', nom: "GIRONES" },
    { codi: '21', nom: "MARESME" },
    { codi: '22', nom: "MONTSIA" },
    { codi: '23', nom: "NOGUERA" },
    { codi: '24', nom: "OSONA" },
    { codi: '25', nom: "PALLARS JUSSA" },
    { codi: '26', nom: "PALLARS SOBIRA" },
    { codi: '27', nom: "PLA D'URGELL" },
    { codi: '28', nom: "PLA DE L'ESTANY" },
    { codi: '29', nom: "PRIORAT" },
    { codi: '30', nom: "RIBERA D'EBRE" },
    { codi: '31', nom: "RIPOLLES" },
    { codi: '32', nom: "SEGARRA" },
    { codi: '33', nom: "SEGRIA" },
    { codi: '34', nom: "SELVA" },
    { codi: '35', nom: "SOLSONES" },
    { codi: '36', nom: "TARRAGONES" },
    { codi: '37', nom: "TERRA ALTA" },
    { codi: '38', nom: "URGELL" },
    { codi: '39', nom: "VALL D'ARAN" },
    { codi: '40', nom: "VALLES OCCIDENTAL" },
    { codi: '41', nom: "VALLES ORIENTAL" },
    { codi: '42', nom: "MOIANES" },
];

export default Comarcas;